---
- hosts: localhost
  connection: local

  vars_files:
    - constants.yaml

  vars_prompt:
    - name: sshpass
      prompt: "Enter your passphrase for SSH key"

  vars:
    - packages_save_path: "/{{ playbook_dir }}/packages"


  tasks:

    # Install packages in official apt and snap store
    - name: Install apt packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - python3-pip 
        - git
        - git-review
        - sshpass
        - gnome-tweaks
        - thunderbird
        - curl
        - net-tools
        - tmux
        - ncdu
        - neofetch
      become: yes

    - name: Install snap packages
      snap:
        name: "{{ item }}"
        classic: yes
      with_items:
        - codium
        - code
        - sublime-text
        - skype
        - telegram-desktop
        - signal-desktop
        - vlc
      become: yes


    # Create packages folder
    - name: Create a packages folder to holds downloaded packages
      file:
        path: "{{ packages_save_path }}"
        state: directory
        mode: "u=rwx,g=rwx,o=rwx"


    # Install bashtop
    - name: Add bashtop repository
      apt_repository:
        repo: 'ppa:bashtop-monitor/bashtop'
        state: present
      become: yes

    - name: Install bashtop with apt
      apt:
        name: bashtop
        update_cache: yes
      become: yes


    # Install FreeTube
    - name: Download FreeTube package
      get_url:
        url: "https://github.com/FreeTubeApp/FreeTube/releases/download/v0.16.0-beta/freetube_{{ FREETUBE_VERSION }}_amd64.deb"
        dest: "{{ packages_save_path }}/freetube_{{ FREETUBE_VERSION }}_amd64.deb"

    - name: Install FreeTube from the downloaded package
      apt:
        deb: "{{ packages_save_path }}/freetube_{{ FREETUBE_VERSION }}_amd64.deb"
        allow_unauthenticated: yes
      become: yes


    # Generate keys
    - name: Generate SSH key
      user:
        name: "{{ansible_user}}"
        generate_ssh_key: yes
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: "~/.ssh/{{SSH_KEY_FILE}}"
        ssh_key_passphrase: "{{ sshpass }}"
        ssh_key_comment: "{{ ansible_user }}@{{ ansible_hostname }}"
        force: no


    # UI Configuration
    - name: Configure the UI elements of the system with gsettings
      shell: |
        gsettings set org.gnome.shell.extensions.dash-to-dock extend-height false
        gsettings set org.gnome.shell.extensions.dash-to-dock transparency-mode FIXED
        gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM
        gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 24
        gsettings set org.gnome.desktop.interface clock-show-date true
        gsettings set org.gnome.desktop.interface clock-show-seconds true
        gsettings set org.gnome.desktop.interface clock-show-weekday true
        gsettings set org.gnome.desktop.interface clock-format 12h
      args:
        executable: /bin/bash


    # Clean up
    - name: Remove packages folder
      file:
        path: "{{ packages_save_path }}"
        state: absent